### ISSUE TITLE
Minor API nitpicks

### ISSUE THREAD

**Issue by alisterburt** [EuanPyle/lil_aretomo#1]
Great job on this Euan! I have a few minor nitpicks on the API I wondered if you would consider changing

- `exe` -> `aretomo_executable`
- `patch_in_x` -> `n_patches_x` (same for y)
-  `run_batchrun` should be called `align_tilt_series_with_aretomo` or similar
=

**Comment by EuanPyle** [comment]
Yep, will do now! Will upload to PyPi when I've finished adding AlignZ
