### ISSUE TITLE
prevent dark images from being removed

### ISSUE THREAD

**Issue by alisterburt** [EuanPyle/lil_aretomo#14]
I think we should prevent dark images from being removed automatically because our detection here isn't super robust, what do you think?

From the manual, this can be achieved by adding the argument `-DarkTol 0.01` to the AreTomo command

**Comment by EuanPyle** [comment]
Yeah, I agree, I don't like any images being removed automatically full stop. Will put in now.

**Comment by EuanPyle** [comment]
Doneee
